import type { Node } from "@xyflow/react";

import type { NodeData } from "@/store/useFlowStore";

export type TemplateFormFieldKind =
  | "text"
  | "url"
  | "textarea"
  | "validator-choice"
  | "storage-name"
  | "storage-fields"
  | "constructor-args";

export interface TemplateFormField {
  id: string;
  label: string;
  kind: TemplateFormFieldKind;
  required: boolean;
  done: boolean;
  helpText: string;
}

export interface TemplateFormSection {
  id: string;
  title: string;
  description: string;
  fields: TemplateFormField[];
}

export interface TemplateFormDefinition {
  title: string;
  description: string;
  sections: TemplateFormSection[];
}

export function getTemplateFormDefinition(params: {
  templateName: string;
  nodeData: NodeData;
  nodes: Node[];
}): TemplateFormDefinition {
  const { templateName, nodeData, nodes } = params;
  const activeNodeTypes = new Set(nodes.map((node) => node.type ?? "unknown"));
  const sections: TemplateFormSection[] = [
    {
      id: "basics",
      title: "Contract basics",
      description:
        "Give this contract a clear name so GenFlow can label the export and generated class.",
      fields: [
        {
          id: "contract-name",
          label: "Contract name",
          kind: "text",
          required: true,
          done: nodeData.contractName.trim().length > 0,
          helpText: "Use a short, clear name for the contract you are creating.",
        },
      ],
    },
  ];

  if (activeNodeTypes.has("webFetchNode") || activeNodeTypes.has("httpNode")) {
    sections.push({
      id: "source",
      title: "Source data",
      description:
        "Tell GenFlow where this contract should read outside information from.",
      fields: [
        {
          id: "url",
          label: "Source URL",
          kind: "url",
          required: true,
          done: nodeData.url.trim().length > 0,
          helpText:
            "Paste the web page or API endpoint the contract should use during execution.",
        },
      ],
    });
  }

  if (activeNodeTypes.has("llmPromptNode")) {
    sections.push({
      id: "ai-behavior",
      title: "AI behavior",
      description:
        "Describe the decision, analysis, or judgment you want the model to make.",
      fields: [
        {
          id: "prompt",
          label: "AI instruction",
          kind: "textarea",
          required: true,
          done: nodeData.prompt.trim().length > 0,
          helpText:
            "Write the instruction in plain language. GenFlow uses this text to build the contract logic.",
        },
        {
          id: "validators",
          label: "Validator count",
          kind: "validator-choice",
          required: false,
          done: nodeData.numValidators > 0,
          helpText:
            "Choose how many validators should check the non-deterministic result.",
        },
      ],
    });
  }

  if (activeNodeTypes.has("storageNode")) {
    sections.push({
      id: "state",
      title: "Saved data",
      description:
        "Control what information this contract stores and the public names it uses.",
      fields: [
        {
          id: "storage-name",
          label: "Main state name",
          kind: "storage-name",
          required: false,
          done: nodeData.storageName.trim().length > 0,
          helpText:
            "Optional. Leave blank to use the default state name generated by GenFlow.",
        },
        {
          id: "storage-fields",
          label: "Extra saved fields",
          kind: "storage-fields",
          required: false,
          done:
            nodeData.storageFields.length === 0 ||
            nodeData.storageFields.every(
              (field) => field.name.trim().length > 0 && field.type.trim().length > 0
            ),
          helpText:
            "Optional. Add more fields only if this contract needs extra saved values.",
        },
      ],
    });
  }

  if (nodeData.constructorArgs.length > 0 || activeNodeTypes.has("initNode")) {
    sections.push({
      id: "launch-settings",
      title: "Launch settings",
      description:
        "Optional constructor inputs let technical teams pass values at deployment time.",
      fields: [
        {
          id: "constructor-args",
          label: "Constructor inputs",
          kind: "constructor-args",
          required: false,
          done:
            nodeData.constructorArgs.length === 0 ||
            nodeData.constructorArgs.every(
              (arg) => arg.name.trim().length > 0 && arg.type.trim().length > 0
            ),
          helpText:
            "Leave this empty unless you know the contract should accept setup values on deploy.",
        },
      ],
    });
  }

  return {
    title: templateName,
    description: `Fill the key setup answers for ${templateName}. GenFlow keeps the contract structure for you in the background.`,
    sections,
  };
}
