/**
 * Hard-coded Python template for a GenLayer Intelligent Contract.
 * Placeholders: {{CONTRACT_NAME}}, {{URL}}, {{PROMPT}}, {{NUM_VALIDATORS}}
 *
 * This template is SAFE-BY-DESIGN: the Python syntax is always valid
 * because the structure is hard-coded and only data values are injected.
 */
export const PYTHON_TEMPLATE = `# { "Depends": "py-genlayer:test" }
from genlayer import *
import json

# ============================================================
# {{CONTRACT_NAME}} — GenLayer Intelligent Contract
# Generated by GenFlow Visual Builder
# Validators: {{NUM_VALIDATORS}}
# ============================================================

class {{CONTRACT_NAME}}(gl.Contract):
    result: str

    def __init__(self):
        self.result = ""

    @gl.public.write
    def analyze(self) -> str:
        """
        Fetches web data and analyzes it using AI with
        the Equivalence Principle for consensus validation.
        """
        def task() -> str:
            # Step 1: Fetch web content
            web_data = gl.nondet.web.render(
                "{{URL}}",
                mode="text"
            )

            # Step 2: AI analysis with LLM
            analysis = gl.nondet.exec_prompt(
                f"""{{PROMPT}}

Web data collected:
{web_data}

Analyze the above data and return a clear, structured result."""
            )
            return analysis.strip()

        # Step 3: Consensus validation via Equivalence Principle
        self.result = gl.eq_principle.prompt_non_comparative(
            task,
            task="Analyze web data with AI",
            criteria="Results should convey equivalent meaning and conclusions"
        )
        return self.result

    @gl.public.view
    def get_result(self) -> str:
        """Returns the latest analysis result."""
        return self.result
`;
