import type { ContractTemplate } from "../templateRegistry";

export const aiArbitratorTemplate: ContractTemplate = {
  id: "ai-arbitrator",
  name: "AI Arbitrator",
  icon: "Scale",
  description: "Fetch web data and use AI to analyze it with consensus validation.",
  category: "AI Analysis",
  placeholders: ["CONTRACT_NAME", "URL", "PROMPT", "NUM_VALIDATORS"],
  requiredNodes: ["initNode", "webFetchNode", "llmPromptNode"],
  defaultNodes: [
    { id: "init-1", type: "initNode", position: { x: 300, y: 0 }, data: {} },
    { id: "webfetch-1", type: "webFetchNode", position: { x: 300, y: 200 }, data: {} },
    { id: "llmprompt-1", type: "llmPromptNode", position: { x: 300, y: 420 }, data: {} },
  ],
  defaultEdges: [
    { id: "edge-init-webfetch", source: "init-1", target: "webfetch-1", animated: true },
    { id: "edge-webfetch-llm", source: "webfetch-1", target: "llmprompt-1", animated: true },
  ],
  template: `# { "Depends": "py-genlayer:test" }
from genlayer import *
import json

# ============================================================
# {{CONTRACT_NAME}} — GenLayer Intelligent Contract
# Generated by GenFlow Visual Builder
# Template: AI Arbitrator
# Validators: {{NUM_VALIDATORS}}
# ============================================================

class {{CONTRACT_NAME}}(gl.Contract):
    result: str

    def __init__(self):
        self.result = ""

    @gl.public.write
    def analyze(self) -> str:
        """
        Fetches web data and analyzes it using AI with
        the Equivalence Principle for consensus validation.
        """
        def task() -> str:
            # Step 1: Fetch web content
            web_data = gl.nondet.web.render(
                "{{URL}}",
                mode="text"
            )

            # Step 2: AI analysis with LLM
            analysis = gl.nondet.exec_prompt(
                f"""{{PROMPT}}

Web data collected:
{web_data}

Analyze the above data and return a clear, structured result."""
            )
            return analysis.strip()

        # Step 3: Consensus validation via Equivalence Principle
        self.result = gl.eq_principle.prompt_non_comparative(
            task,
            task="Analyze web data with AI",
            criteria="Results should convey equivalent meaning and conclusions"
        )
        return self.result

    @gl.public.view
    def get_result(self) -> str:
        """Returns the latest analysis result."""
        return self.result
`,
};
