import type { ContractTemplate } from "../templateRegistry";

export const aiGameTemplate: ContractTemplate = {
  id: "ai-game",
  name: "AI Gaming",
  description:
    "Consensus-driven AI gameplay where player actions are judged and state updates persist across rounds.",
  icon: "Gamepad2",
  category: "Game",
  tags: ["Gameplay", "Consensus", "Rounds"],
  featured: true,
  placeholders: ["CONTRACT_NAME", "PROMPT"],
  requiredNodes: ["initNode", "storageNode", "llmPromptNode", "consensusNode", "outputNode"],
  defaultNodes: [
    { id: "init-1", type: "initNode", position: { x: 350, y: 50 }, data: {} },
    { id: "storage-1", type: "storageNode", position: { x: 350, y: 210 }, data: {} },
    { id: "llmprompt-1", type: "llmPromptNode", position: { x: 350, y: 390 }, data: {} },
    { id: "consensus-1", type: "consensusNode", position: { x: 350, y: 570 }, data: {} },
    { id: "output-1", type: "outputNode", position: { x: 350, y: 750 }, data: {} },
  ],
  defaultEdges: [
    { id: "e-init-storage", source: "init-1", target: "storage-1", animated: true },
    { id: "e-storage-llm", source: "storage-1", target: "llmprompt-1", animated: true },
    { id: "e-llm-consensus", source: "llmprompt-1", target: "consensus-1", animated: true },
    { id: "e-consensus-output", source: "consensus-1", target: "output-1", animated: true },
  ],
  template: `# { "Depends": "py-genlayer:test" }
from genlayer import *
import json


# ==========================================================
# {{CONTRACT_NAME}} - GenLayer Intelligent Contract
# Generated by GenFlow Visual Builder
# Template: AI Gaming
# ==========================================================

class {{CONTRACT_NAME}}(gl.Contract):
    game_active: bool

    def __init__(self, initial_state: bool):
        self.game_active = initial_state

    @gl.public.write
    def play(self, player_input: str) -> None:
        """
        Player submits a move. AI decides the round outcome using
        comparative consensus across validators.
        """
        if not self.game_active:
            return

        game_state = self.game_active

        prompt = f"""
{{PROMPT}}

Current game state: {game_state}
Player says: {player_input}

Respond using ONLY the following JSON format:
{{{{
    "reasoning": str,    # Your reasoning for the decision
    "player_wins": bool  # Whether the player wins this round
}}}}
It is mandatory that you respond only using the JSON format above.
"""

        def get_ai_decision():
            result = gl.nondet.exec_prompt(prompt)
            result = result.replace("\`\`\`json", "").replace("\`\`\`", "")
            return result

        result = gl.eq_principle.prompt_comparative(
            get_ai_decision, "The value of player_wins has to match"
        )
        parsed_result = json.loads(result)
        assert isinstance(parsed_result["player_wins"], bool)
        self.game_active = not parsed_result["player_wins"]

    @gl.public.view
    def get_game_state(self) -> bool:
        return self.game_active
`,
};
