import type { ContractTemplate } from "../templateRegistry";

export const aiGameTemplate: ContractTemplate = {
  id: "ai-game",
  name: "AI Game",
  description:
    "AI-powered interactive game. Users challenge AI — it decides the outcome via consensus.",
  icon: "Gamepad2",
  category: "Game",
  placeholders: ["CONTRACT_NAME", "PROMPT"],
  requiredNodes: ["initNode", "llmPromptNode"],
  defaultNodes: [
    { id: "init-1", type: "initNode", position: { x: 350, y: 50 }, data: {} },
    { id: "llmprompt-1", type: "llmPromptNode", position: { x: 350, y: 250 }, data: {} },
    { id: "output-1", type: "outputNode", position: { x: 350, y: 500 }, data: {} },
  ],
  defaultEdges: [
    { id: "e-init-llm", source: "init-1", target: "llmprompt-1", animated: true },
    { id: "e-llm-output", source: "llmprompt-1", target: "output-1", animated: true },
  ],
  template: `# { "Depends": "py-genlayer:test" }
from genlayer import *
import json


# ==========================================================
# {{CONTRACT_NAME}} — GenLayer Intelligent Contract
# Generated by GenFlow Visual Builder
# Template: AI Game
# ==========================================================

class {{CONTRACT_NAME}}(gl.Contract):
    game_active: bool

    def __init__(self, initial_state: bool):
        self.game_active = initial_state

    @gl.public.write
    def play(self, player_input: str) -> None:
        """
        Player submits a request. AI decides the outcome using
        comparative consensus (validators must agree on the result).
        """
        if not self.game_active:
            return

        game_state = self.game_active

        prompt = f"""
{{PROMPT}}

Current game state: {game_state}
Player says: {player_input}

Respond using ONLY the following JSON format:
{{{{
    "reasoning": str,    // Your reasoning for the decision
    "player_wins": bool  // Whether the player wins this round
}}}}
It is mandatory that you respond only using the JSON format above.
"""

        def get_ai_decision():
            result = gl.nondet.exec_prompt(prompt)
            result = result.replace("\`\`\`json", "").replace("\`\`\`", "")
            return result

        result = gl.eq_principle.prompt_comparative(
            get_ai_decision, "The value of player_wins has to match"
        )
        parsed_result = json.loads(result)
        assert isinstance(parsed_result["player_wins"], bool)
        self.game_active = not parsed_result["player_wins"]

    @gl.public.view
    def get_game_state(self) -> bool:
        return self.game_active
`,
};
