import type { ContractTemplate } from "../templateRegistry";

export const aiGovernanceTemplate: ContractTemplate = {
  id: "ai-governance",
  name: "AI Governance",
  icon: "Landmark",
  description:
    "Coordinate proposals, decisions, and action plans with AI-backed consensus for teams or DAOs.",
  category: "Governance",
  tags: ["DAOs", "Agents", "Coordination"],
  featured: true,
  placeholders: ["CONTRACT_NAME", "PROMPT", "NUM_VALIDATORS"],
  requiredNodes: ["initNode", "storageNode", "llmPromptNode", "consensusNode", "outputNode"],
  defaultNodes: [
    { id: "init-1", type: "initNode", position: { x: 320, y: 20 }, data: {} },
    { id: "storage-1", type: "storageNode", position: { x: 320, y: 180 }, data: {} },
    { id: "llm-1", type: "llmPromptNode", position: { x: 320, y: 360 }, data: {} },
    { id: "consensus-1", type: "consensusNode", position: { x: 320, y: 540 }, data: {} },
    { id: "output-1", type: "outputNode", position: { x: 320, y: 720 }, data: {} },
  ],
  defaultEdges: [
    { id: "e-init-storage", source: "init-1", target: "storage-1", animated: true },
    { id: "e-storage-llm", source: "storage-1", target: "llm-1", animated: true },
    { id: "e-llm-consensus", source: "llm-1", target: "consensus-1", animated: true },
    { id: "e-consensus-output", source: "consensus-1", target: "output-1", animated: true },
  ],
  template: `# { "Depends": "py-genlayer:test" }
from genlayer import *
import json

# ============================================================
# {{CONTRACT_NAME}} - GenLayer Intelligent Contract
# Generated by GenFlow Visual Builder
# Template: AI Governance
# Validators: {{NUM_VALIDATORS}}
# ============================================================

class {{CONTRACT_NAME}}(gl.Contract):
    current_agenda: str
    last_decision: str
    decision_count: u256
    review_required: bool

    def __init__(self):
        self.current_agenda = ""
        self.last_decision = ""
        self.decision_count = u256(0)
        self.review_required = False

    @gl.public.write
    def submit_agenda(self, agenda: str) -> None:
        """Stores a new agenda item that needs coordinated review."""
        self.current_agenda = agenda
        self.review_required = True

    @gl.public.write
    def coordinate(self, context: str) -> str:
        """
        Uses AI consensus to recommend the next governance action
        for the current agenda item.
        """
        if self.current_agenda == "":
            raise gl.vm.UserError("No agenda submitted")

        agenda = self.current_agenda

        def task() -> str:
            recommendation = gl.nondet.exec_prompt(
                f"""{{PROMPT}}

Agenda:
{agenda}

Execution context:
{context}

Respond with ONLY valid JSON:
{{
    "decision": "APPROVE" or "REVIEW" or "DEFER",
    "actions": ["short action items"],
    "rationale": "brief explanation"
}}"""
            )
            return recommendation.strip()

        self.last_decision = gl.eq_principle.prompt_non_comparative(
            task,
            task="Coordinate a governance decision",
            criteria="Decision, actions, and rationale should be semantically equivalent"
        )
        self.decision_count += u256(1)
        self.review_required = False
        return self.last_decision

    @gl.public.view
    def get_agenda(self) -> str:
        return self.current_agenda

    @gl.public.view
    def get_last_decision(self) -> str:
        return self.last_decision
`,
};
