import type { ContractTemplate } from "../templateRegistry";

export const contentFilterTemplate: ContractTemplate = {
  id: "content-filter",
  name: "Content Filter",
  icon: "Shield",
  description: "AI-powered content moderation with event emission and consensus.",
  category: "Moderation",
  placeholders: ["CONTRACT_NAME", "PROMPT", "NUM_VALIDATORS"],
  requiredNodes: ["initNode", "llmPromptNode", "eventNode", "outputNode"],
  defaultNodes: [
    { id: "init-1", type: "initNode", position: { x: 300, y: 0 }, data: {} },
    { id: "llmprompt-1", type: "llmPromptNode", position: { x: 300, y: 200 }, data: {} },
    { id: "event-1", type: "eventNode", position: { x: 300, y: 440 }, data: {} },
    { id: "output-1", type: "outputNode", position: { x: 300, y: 640 }, data: {} },
  ],
  defaultEdges: [
    { id: "edge-init-llm", source: "init-1", target: "llmprompt-1", animated: true },
    { id: "edge-llm-event", source: "llmprompt-1", target: "event-1", animated: true },
    { id: "edge-event-output", source: "event-1", target: "output-1", animated: true },
  ],
  template: `# { "Depends": "py-genlayer:test" }
from genlayer import *
import json

# ============================================================
# {{CONTRACT_NAME}} — GenLayer Intelligent Contract
# Generated by GenFlow Visual Builder
# Template: Content Filter
# Validators: {{NUM_VALIDATORS}}
# ============================================================

class {{CONTRACT_NAME}}(gl.Contract):
    moderation_result: str
    flagged_count: int

    def __init__(self):
        self.moderation_result = ""
        self.flagged_count = 0

    @gl.public.write
    def moderate_content(self, content: str) -> str:
        """
        Analyzes content using AI moderation with
        consensus-based validation for fair decisions.
        """
        def task() -> str:
            analysis = gl.nondet.exec_prompt(
                f"""{{PROMPT}}

Content to moderate:
{content}

Analyze the content and return a JSON result:
{{
    "status": "SAFE" or "FLAGGED" or "BLOCKED",
    "categories": ["list of detected categories"],
    "confidence": 0.0 to 1.0,
    "reason": "brief explanation"
}}"""
            )
            return analysis.strip()

        self.moderation_result = gl.eq_principle.prompt_non_comparative(
            task,
            task="Moderate content with AI",
            criteria="Moderation decisions should agree on status and key categories"
        )

        # Track flagged content count
        if '"FLAGGED"' in self.moderation_result or '"BLOCKED"' in self.moderation_result:
            self.flagged_count += 1

        return self.moderation_result

    @gl.public.view
    def get_result(self) -> str:
        """Returns the latest moderation result."""
        return self.moderation_result

    @gl.public.view
    def get_flagged_count(self) -> int:
        """Returns total number of flagged/blocked content."""
        return self.flagged_count
`,
};
