import type { ContractTemplate } from "../templateRegistry";

export const customComposeTemplate: ContractTemplate = {
  id: "custom-compose",
  name: "Custom Compose",
  description:
    "Start blank and compose your contract by dragging blocks. Code generates dynamically.",
  icon: "Puzzle",
  category: "Custom",
  placeholders: ["CONTRACT_NAME", "URL", "PROMPT", "NUM_VALIDATORS", "FIELD_NAME"],
  requiredNodes: ["initNode"],
  defaultNodes: [
    { id: "init-1", type: "initNode", position: { x: 350, y: 50 }, data: {} },
  ],
  defaultEdges: [],
  // This template is special — the code is built dynamically by composeCode()
  // This string is just the fallback if composeCode isn't used
  template: `# { "Depends": "py-genlayer:test" }
from genlayer import *
import json


# ==========================================================
# {{CONTRACT_NAME}} — GenLayer Intelligent Contract
# Generated by GenFlow Visual Builder
# Template: Custom Compose
# ==========================================================

class {{CONTRACT_NAME}}(gl.Contract):
    result: str

    def __init__(self):
        self.result = ""

    @gl.public.view
    def get_result(self) -> str:
        return self.result
`,
};
