import type { ContractTemplate } from "../templateRegistry";

export const daoVoteTemplate: ContractTemplate = {
  id: "dao-vote",
  name: "DAO Vote",
  icon: "Vote",
  description: "Create decentralized proposals with AI-evaluated voting and consensus.",
  category: "Governance",
  placeholders: ["CONTRACT_NAME", "PROMPT", "NUM_VALIDATORS"],
  requiredNodes: ["initNode", "storageNode", "llmPromptNode", "outputNode"],
  defaultNodes: [
    { id: "init-1", type: "initNode", position: { x: 300, y: 0 }, data: {} },
    { id: "storage-1", type: "storageNode", position: { x: 300, y: 200 }, data: {} },
    { id: "llmprompt-1", type: "llmPromptNode", position: { x: 300, y: 420 }, data: {} },
    { id: "output-1", type: "outputNode", position: { x: 300, y: 640 }, data: {} },
  ],
  defaultEdges: [
    { id: "edge-init-storage", source: "init-1", target: "storage-1", animated: true },
    { id: "edge-storage-llm", source: "storage-1", target: "llmprompt-1", animated: true },
    { id: "edge-llm-output", source: "llmprompt-1", target: "output-1", animated: true },
  ],
  template: `# { "Depends": "py-genlayer:test" }
from genlayer import *
import json

# ============================================================
# {{CONTRACT_NAME}} — GenLayer Intelligent Contract
# Generated by GenFlow Visual Builder
# Template: DAO Vote
# Validators: {{NUM_VALIDATORS}}
# ============================================================

class {{CONTRACT_NAME}}(gl.Contract):
    proposal: str
    vote_result: str
    is_resolved: bool

    def __init__(self):
        self.proposal = ""
        self.vote_result = ""
        self.is_resolved = False

    @gl.public.write
    def create_proposal(self, proposal_text: str) -> None:
        """Creates a new proposal for voting."""
        self.proposal = proposal_text
        self.is_resolved = False
        self.vote_result = ""

    @gl.public.write
    def evaluate_proposal(self) -> str:
        """
        Uses AI to evaluate the proposal and reach consensus
        on whether it should be approved or rejected.
        """
        proposal = self.proposal

        def task() -> str:
            analysis = gl.nondet.exec_prompt(
                f"""{{PROMPT}}

Proposal to evaluate:
{proposal}

Analyze this proposal carefully. Consider:
1. Feasibility and practicality
2. Potential risks and benefits
3. Community impact

Return your verdict as JSON: {{"verdict": "APPROVE" or "REJECT", "reasoning": "..."}}"""
            )
            return analysis.strip()

        self.vote_result = gl.eq_principle.prompt_non_comparative(
            task,
            task="Evaluate DAO proposal",
            criteria="Verdicts should reach the same conclusion with similar reasoning"
        )
        self.is_resolved = True
        return self.vote_result

    @gl.public.view
    def get_proposal(self) -> str:
        """Returns the current proposal text."""
        return self.proposal

    @gl.public.view
    def get_result(self) -> str:
        """Returns the voting result."""
        return self.vote_result
`,
};
