import type { ContractTemplate } from "../templateRegistry";

export const futureOfWorkTemplate: ContractTemplate = {
  id: "future-of-work",
  name: "Future of Work",
  icon: "Briefcase",
  description:
    "Review deliverables against a live rubric, track approvals, and keep an auditable AI review trail.",
  category: "Operations",
  tags: ["Deliverables", "Reviews", "Reputation"],
  featured: true,
  placeholders: ["CONTRACT_NAME", "URL", "PROMPT", "NUM_VALIDATORS"],
  requiredNodes: ["initNode", "storageNode", "webFetchNode", "llmPromptNode", "outputNode"],
  defaultNodes: [
    { id: "init-1", type: "initNode", position: { x: 320, y: 20 }, data: {} },
    { id: "storage-1", type: "storageNode", position: { x: 320, y: 180 }, data: {} },
    { id: "web-1", type: "webFetchNode", position: { x: 320, y: 360 }, data: {} },
    { id: "llm-1", type: "llmPromptNode", position: { x: 320, y: 540 }, data: {} },
    { id: "output-1", type: "outputNode", position: { x: 320, y: 720 }, data: {} },
  ],
  defaultEdges: [
    { id: "e-init-storage", source: "init-1", target: "storage-1", animated: true },
    { id: "e-storage-web", source: "storage-1", target: "web-1", animated: true },
    { id: "e-web-llm", source: "web-1", target: "llm-1", animated: true },
    { id: "e-llm-output", source: "llm-1", target: "output-1", animated: true },
  ],
  template: `# { "Depends": "py-genlayer:test" }
from genlayer import *
import json

# ============================================================
# {{CONTRACT_NAME}} - GenLayer Intelligent Contract
# Generated by GenFlow Visual Builder
# Template: Future of Work
# Validators: {{NUM_VALIDATORS}}
# ============================================================

class {{CONTRACT_NAME}}(gl.Contract):
    work_brief: str
    latest_review: str
    approved_count: u256
    rejected_count: u256

    def __init__(self):
        self.work_brief = ""
        self.latest_review = ""
        self.approved_count = u256(0)
        self.rejected_count = u256(0)

    @gl.public.write
    def set_work_brief(self, brief: str) -> None:
        """Stores the expected outcome for a work package."""
        self.work_brief = brief

    @gl.public.write
    def review_submission(self, submission_url: str) -> str:
        """
        Fetches a submission and evaluates it against a rubric
        defined by the project team.
        """
        if self.work_brief == "":
            raise gl.vm.UserError("Set a work brief before reviewing submissions")

        work_brief = self.work_brief

        def task() -> str:
            rubric = gl.nondet.web.render("{{URL}}", mode="text")
            submission = gl.nondet.web.render(submission_url, mode="text")

            review = gl.nondet.exec_prompt(
                f"""{{PROMPT}}

Work brief:
{work_brief}

Rubric:
{rubric}

Submission:
{submission}

Respond with ONLY valid JSON:
{{
    "status": "APPROVE" or "REJECT" or "REVISE",
    "score": 0 to 100,
    "summary": "short explanation",
    "next_steps": ["specific changes or follow-up actions"]
}}"""
            )
            return review.strip()

        self.latest_review = gl.eq_principle.prompt_non_comparative(
            task,
            task="Review submitted work against a rubric",
            criteria="Status, score band, and key recommendations should be semantically equivalent"
        )

        if '"APPROVE"' in self.latest_review:
            self.approved_count += u256(1)
        elif '"REJECT"' in self.latest_review:
            self.rejected_count += u256(1)

        return self.latest_review

    @gl.public.view
    def get_latest_review(self) -> str:
        return self.latest_review

    @gl.public.view
    def get_review_stats(self) -> str:
        return json.dumps({
            "approved_count": str(self.approved_count),
            "rejected_count": str(self.rejected_count),
        })
`,
};
