import type { ContractTemplate } from "../templateRegistry";

export const onchainJusticeTemplate: ContractTemplate = {
  id: "onchain-justice",
  name: "Onchain Justice",
  icon: "Scale",
  description:
    "Resolve disputes from evidence bundles and policy rules with a consensus-backed AI ruling.",
  category: "Justice",
  tags: ["Disputes", "Evidence", "Rulings"],
  featured: true,
  placeholders: ["CONTRACT_NAME", "URL", "PROMPT", "NUM_VALIDATORS"],
  requiredNodes: ["initNode", "storageNode", "webFetchNode", "llmPromptNode", "consensusNode", "outputNode"],
  defaultNodes: [
    { id: "init-1", type: "initNode", position: { x: 320, y: 20 }, data: {} },
    { id: "storage-1", type: "storageNode", position: { x: 320, y: 180 }, data: {} },
    { id: "web-1", type: "webFetchNode", position: { x: 320, y: 360 }, data: {} },
    { id: "llm-1", type: "llmPromptNode", position: { x: 320, y: 540 }, data: {} },
    { id: "consensus-1", type: "consensusNode", position: { x: 320, y: 720 }, data: {} },
    { id: "output-1", type: "outputNode", position: { x: 320, y: 900 }, data: {} },
  ],
  defaultEdges: [
    { id: "e-init-storage", source: "init-1", target: "storage-1", animated: true },
    { id: "e-storage-web", source: "storage-1", target: "web-1", animated: true },
    { id: "e-web-llm", source: "web-1", target: "llm-1", animated: true },
    { id: "e-llm-consensus", source: "llm-1", target: "consensus-1", animated: true },
    { id: "e-consensus-output", source: "consensus-1", target: "output-1", animated: true },
  ],
  template: `# { "Depends": "py-genlayer:test" }
from genlayer import *
import json

# ============================================================
# {{CONTRACT_NAME}} - GenLayer Intelligent Contract
# Generated by GenFlow Visual Builder
# Template: Onchain Justice
# Validators: {{NUM_VALIDATORS}}
# ============================================================

class {{CONTRACT_NAME}}(gl.Contract):
    case_summary: str
    evidence_url: str
    latest_ruling: str
    case_status: str

    def __init__(self):
        self.case_summary = ""
        self.evidence_url = ""
        self.latest_ruling = ""
        self.case_status = "open"

    @gl.public.write
    def file_case(self, claim: str, evidence_url: str) -> None:
        """Stores the dispute summary and the evidence bundle URL."""
        self.case_summary = claim
        self.evidence_url = evidence_url
        self.case_status = "under_review"

    @gl.public.write
    def resolve_case(self) -> str:
        """
        Pulls evidence and rulebook context, then asks validators
        to converge on a fair ruling.
        """
        if self.case_summary == "" or self.evidence_url == "":
            raise gl.vm.UserError("Case summary and evidence URL are required")

        case_summary = self.case_summary
        evidence_url = self.evidence_url

        def task() -> str:
            rulebook = gl.nondet.web.render("{{URL}}", mode="text")
            evidence = gl.nondet.web.render(evidence_url, mode="text")

            ruling = gl.nondet.exec_prompt(
                f"""{{PROMPT}}

Dispute summary:
{case_summary}

Rulebook:
{rulebook}

Evidence bundle:
{evidence}

Respond with ONLY valid JSON:
{{
    "verdict": "CLAIMANT" or "RESPONDENT" or "PARTIAL",
    "confidence": 0.0 to 1.0,
    "reasoning": "brief explanation",
    "remedy": "short remedy or next action"
}}"""
            )
            return ruling.strip()

        self.latest_ruling = gl.eq_principle.prompt_non_comparative(
            task,
            task="Resolve a dispute from evidence and policy",
            criteria="Verdict, remedy, and reasoning should be semantically equivalent"
        )
        self.case_status = "resolved"
        return self.latest_ruling

    @gl.public.view
    def get_case_status(self) -> str:
        return self.case_status

    @gl.public.view
    def get_latest_ruling(self) -> str:
        return self.latest_ruling
`,
};
