import type { ContractTemplate } from "../templateRegistry";

export const oracleBenchmarkTemplate: ContractTemplate = {
  id: "oracle-benchmark",
  name: "Oracle Benchmark",
  icon: "FlaskConical",
  description:
    "Benchmark live oracle or prediction sources and produce a structured confidence report for operators.",
  category: "Research",
  tags: ["Benchmarks", "Routing", "Risk Checks"],
  featured: true,
  placeholders: ["CONTRACT_NAME", "URL", "PROMPT", "NUM_VALIDATORS"],
  requiredNodes: ["initNode", "webFetchNode", "llmPromptNode", "consensusNode", "outputNode"],
  defaultNodes: [
    { id: "init-1", type: "initNode", position: { x: 320, y: 20 }, data: {} },
    { id: "web-1", type: "webFetchNode", position: { x: 320, y: 200 }, data: {} },
    { id: "llm-1", type: "llmPromptNode", position: { x: 320, y: 380 }, data: {} },
    { id: "consensus-1", type: "consensusNode", position: { x: 320, y: 560 }, data: {} },
    { id: "output-1", type: "outputNode", position: { x: 320, y: 740 }, data: {} },
  ],
  defaultEdges: [
    { id: "e-init-web", source: "init-1", target: "web-1", animated: true },
    { id: "e-web-llm", source: "web-1", target: "llm-1", animated: true },
    { id: "e-llm-consensus", source: "llm-1", target: "consensus-1", animated: true },
    { id: "e-consensus-output", source: "consensus-1", target: "output-1", animated: true },
  ],
  template: `# { "Depends": "py-genlayer:test" }
from genlayer import *
import json

# ============================================================
# {{CONTRACT_NAME}} - GenLayer Intelligent Contract
# Generated by GenFlow Visual Builder
# Template: Oracle Benchmark
# Validators: {{NUM_VALIDATORS}}
# ============================================================

class {{CONTRACT_NAME}}(gl.Contract):
    latest_report: str
    last_source: str
    benchmark_count: u256

    def __init__(self):
        self.latest_report = ""
        self.last_source = "{{URL}}"
        self.benchmark_count = u256(0)

    @gl.public.write
    def benchmark(self) -> str:
        """
        Fetches a live source and asks validators to align on
        a structured benchmark report.
        """
        source_url = self.last_source

        def task() -> str:
            source_data = gl.nondet.web.render(source_url, mode="text")

            report = gl.nondet.exec_prompt(
                f"""{{PROMPT}}

Source URL:
{source_url}

Observed source data:
{source_data}

Respond with ONLY valid JSON:
{{
    "signal": "bullish" or "bearish" or "neutral",
    "confidence": 0.0 to 1.0,
    "anomalies": ["list of anomalies or gaps"],
    "recommendation": "route, hold, or investigate"
}}"""
            )
            return report.strip()

        self.latest_report = gl.eq_principle.prompt_non_comparative(
            task,
            task="Benchmark a live oracle or prediction source",
            criteria="Signal, confidence band, and anomalies should be semantically equivalent"
        )
        self.benchmark_count += u256(1)
        return self.latest_report

    @gl.public.view
    def get_latest_report(self) -> str:
        return self.latest_report

    @gl.public.view
    def get_source(self) -> str:
        return self.last_source
`,
};
