import type { ContractTemplate } from "../templateRegistry";

export const predictionMarketTemplate: ContractTemplate = {
  id: "prediction-market",
  name: "Prediction Market",
  description:
    "Fetch match results from web and resolve predictions with AI + strict consensus.",
  icon: "Trophy",
  category: "DeFi",
  placeholders: ["CONTRACT_NAME", "URL", "PROMPT"],
  requiredNodes: ["initNode", "webFetchNode", "llmPromptNode"],
  defaultNodes: [
    { id: "init-1", type: "initNode", position: { x: 350, y: 30 }, data: {} },
    { id: "webfetch-1", type: "webFetchNode", position: { x: 350, y: 200 }, data: {} },
    { id: "llmprompt-1", type: "llmPromptNode", position: { x: 350, y: 400 }, data: {} },
    { id: "output-1", type: "outputNode", position: { x: 350, y: 650 }, data: {} },
  ],
  defaultEdges: [
    { id: "e-init-web", source: "init-1", target: "webfetch-1", animated: true },
    { id: "e-web-llm", source: "webfetch-1", target: "llmprompt-1", animated: true },
    { id: "e-llm-output", source: "llmprompt-1", target: "output-1", animated: true },
  ],
  template: `# { "Depends": "py-genlayer:test" }
from genlayer import *
import json
import typing


# ==========================================================
# {{CONTRACT_NAME}} — GenLayer Intelligent Contract
# Generated by GenFlow Visual Builder
# Template: Prediction Market
# ==========================================================

class {{CONTRACT_NAME}}(gl.Contract):
    has_resolved: bool
    team1: str
    team2: str
    resolution_url: str
    winner: u256
    score: str

    def __init__(self, team1: str, team2: str):
        self.has_resolved = False
        self.resolution_url = "{{URL}}"
        self.team1 = team1
        self.team2 = team2
        self.winner = u256(0)
        self.score = ""

    @gl.public.write
    def resolve(self) -> typing.Any:
        """
        Fetches match data from web and uses AI to determine the winner.
        Validated through strict consensus.
        """
        if self.has_resolved:
            raise gl.vm.UserError("Already resolved")

        market_resolution_url = self.resolution_url
        team1 = self.team1
        team2 = self.team2

        def get_match_result() -> typing.Any:
            web_data = gl.nondet.web.render(market_resolution_url, mode="text")

            task = f"""
{{PROMPT}}

Data source URL: {market_resolution_url}
Team 1: {team1}
Team 2: {team2}

Web page content:
{web_data}

Respond with ONLY this JSON format:
{{{{
    "score": str,   // e.g. "1:2", or "-" if not resolved
    "winner": int,  // 1 or 2 for winning team, 0 for draw, -1 if not finished
}}}}
"""
            result = (
                gl.nondet.exec_prompt(task)
                .replace("\`\`\`json", "")
                .replace("\`\`\`", "")
            )
            return json.loads(result)

        result_json = gl.eq_principle.strict_eq(get_match_result)

        if result_json["winner"] > -1:
            self.has_resolved = True
            self.winner = result_json["winner"]
            self.score = result_json["score"]

        return result_json

    @gl.public.view
    def get_resolution_data(self) -> dict[str, typing.Any]:
        return {
            "winner": self.winner,
            "score": self.score,
            "has_resolved": self.has_resolved,
        }
`,
};
