import type { ContractTemplate } from "../templateRegistry";

export const priceOracleTemplate: ContractTemplate = {
  id: "price-oracle",
  name: "Price Oracle",
  icon: "TrendingUp",
  description: "Fetch real-time price data from the web and validate with consensus.",
  category: "DeFi",
  placeholders: ["CONTRACT_NAME", "URL", "NUM_VALIDATORS"],
  requiredNodes: ["initNode", "webFetchNode", "outputNode"],
  defaultNodes: [
    { id: "init-1", type: "initNode", position: { x: 300, y: 0 }, data: {} },
    { id: "webfetch-1", type: "webFetchNode", position: { x: 300, y: 200 }, data: {} },
    { id: "output-1", type: "outputNode", position: { x: 300, y: 420 }, data: {} },
  ],
  defaultEdges: [
    { id: "edge-init-webfetch", source: "init-1", target: "webfetch-1", animated: true },
    { id: "edge-webfetch-output", source: "webfetch-1", target: "output-1", animated: true },
  ],
  template: `# { "Depends": "py-genlayer:test" }
from genlayer import *
import json

# ============================================================
# {{CONTRACT_NAME}} — GenLayer Intelligent Contract
# Generated by GenFlow Visual Builder
# Template: Price Oracle
# Validators: {{NUM_VALIDATORS}}
# ============================================================

class {{CONTRACT_NAME}}(gl.Contract):
    price: str
    last_source: str

    def __init__(self):
        self.price = ""
        self.last_source = ""

    @gl.public.write
    def fetch_price(self) -> str:
        """
        Fetches price data from the web and validates
        using comparative consensus (numeric tolerance).
        """
        def task() -> str:
            web_data = gl.nondet.web.render(
                "{{URL}}",
                mode="text"
            )

            price_extraction = gl.nondet.exec_prompt(
                f"""Extract the main price or numeric value from this web data.
Return ONLY the numeric value (e.g., "42850.50"), no other text.

Web data:
{web_data}"""
            )
            return price_extraction.strip()

        self.price = gl.eq_principle.prompt_comparative(
            task,
            task="Extract price from web data",
            tolerance=0.05
        )
        self.last_source = "{{URL}}"
        return self.price

    @gl.public.view
    def get_price(self) -> str:
        """Returns the latest fetched price."""
        return self.price

    @gl.public.view
    def get_source(self) -> str:
        """Returns the data source URL."""
        return self.last_source
`,
};
