import type { ContractTemplate } from "../templateRegistry";

export const simpleStorageTemplate: ContractTemplate = {
  id: "simple-storage",
  name: "Simple Storage",
  description: "Basic on-chain storage. Read and write string data.",
  icon: "HardDrive",
  category: "Storage",
  placeholders: ["CONTRACT_NAME", "FIELD_NAME"],
  requiredNodes: ["initNode"],
  defaultNodes: [
    { id: "init-1", type: "initNode", position: { x: 350, y: 50 }, data: {} },
    { id: "storage-1", type: "storageNode", position: { x: 350, y: 250 }, data: {} },
    { id: "output-1", type: "outputNode", position: { x: 350, y: 450 }, data: {} },
  ],
  defaultEdges: [
    { id: "e-init-storage", source: "init-1", target: "storage-1", animated: true },
    { id: "e-storage-output", source: "storage-1", target: "output-1", animated: true },
  ],
  template: `# { "Depends": "py-genlayer:test" }
from genlayer import *


# ==========================================================
# {{CONTRACT_NAME}} — GenLayer Intelligent Contract
# Generated by GenFlow Visual Builder
# Template: Simple Storage
# ==========================================================

class {{CONTRACT_NAME}}(gl.Contract):
    {{FIELD_NAME}}: str

    def __init__(self, initial_value: str):
        self.{{FIELD_NAME}} = initial_value

    @gl.public.view
    def get_{{FIELD_NAME}}(self) -> str:
        return self.{{FIELD_NAME}}

    @gl.public.write
    def update_{{FIELD_NAME}}(self, new_value: str) -> None:
        self.{{FIELD_NAME}} = new_value
`,
};
