"use client";

import { Handle, Position } from "@xyflow/react";
import { FileCode, Plus, X, ChevronDown, ChevronRight, Wrench } from "lucide-react";
import { useFlowStore } from "@/store/useFlowStore";
import { useState } from "react";

const GENVM_TYPES = [
  "str",
  "bool",
  "u256",
  "u128",
  "u64",
  "u32",
  "i256",
  "bigint",
  "Address",
  "DynArray[str]",
  "DynArray[u256]",
  "DynArray[Address]",
  "TreeMap[str, str]",
  "TreeMap[Address, str]",
  "TreeMap[Address, u256]",
];

const PYTHON_KEYWORDS = new Set([
  "False","None","True","and","as","assert","async","await",
  "break","class","continue","def","del","elif","else","except",
  "finally","for","from","global","if","import","in","is","lambda",
  "nonlocal","not","or","pass","raise","return","self","try","while",
  "with","yield",
]);

/**
 * Names auto-generated by composeCode.ts depending on which nodes are present.
 * If user redefines them, type annotations conflict with generated methods.
 */
const SYSTEM_RESERVED_NAMES = new Set([
  "result",           // LLM / Web / Output nodes write str
  "external_result", // HTTP node
  "consensus_result",// consensus wrapper
  "owner",           // Payable node
  "total_received",  // Payable node
  "items",           // Storage node (list)
  "records",         // Storage node (dict)
  "db",              // VecDB node
  "event_count",     // Event node
]);

function isValidFieldName(name: string): boolean {
  if (!name || name.trim() === "") return false;
  if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(name)) return false;
  if (PYTHON_KEYWORDS.has(name)) return false;
  if (SYSTEM_RESERVED_NAMES.has(name)) return false;
  return true;
}

function fieldNameError(name: string): string | null {
  if (!name || name.trim() === "") return null;
  if (/^\d/.test(name)) return "Cannot start with a digit";
  if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(name)) return "Use only letters, digits, underscores";
  if (PYTHON_KEYWORDS.has(name)) return `'${name}' is a Python keyword`;
  if (SYSTEM_RESERVED_NAMES.has(name)) return `'${name}' is used internally — pick a different name`;
  return null;
}


export default function InitNode() {
  const contractName = useFlowStore((s) => s.nodeData.contractName);
  const setContractName = useFlowStore((s) => s.setContractName);
  const storageFields = useFlowStore((s) => s.nodeData.storageFields);
  const addStorageField = useFlowStore((s) => s.addStorageField);
  const updateStorageField = useFlowStore((s) => s.updateStorageField);
  const removeStorageField = useFlowStore((s) => s.removeStorageField);
  const constructorArgs = useFlowStore((s) => s.nodeData.constructorArgs);
  const addConstructorArg = useFlowStore((s) => s.addConstructorArg);
  const updateConstructorArg = useFlowStore((s) => s.updateConstructorArg);
  const removeConstructorArg = useFlowStore((s) => s.removeConstructorArg);

  const [showCtorArgs, setShowCtorArgs] = useState(false);
  const isEmpty = contractName.trim() === "";

  return (
    <div className={`glass-card w-[300px] ${isEmpty ? "node-error" : ""}`}>
      {/* Header */}
      <div className="flex items-center gap-2 px-4 py-2.5 rounded-none bg-surface border-b border-border">
        <FileCode className="w-4 h-4 text-foreground" />
        <span className="text-xs font-display font-medium text-foreground uppercase tracking-widest">
          Init Contract
        </span>
      </div>

      {/* Body */}
      <div className="px-4 py-3 space-y-3">
        {/* Contract Name */}
        <div>
          <label className="block text-[11px] text-muted mb-1.5 uppercase tracking-widest">
            Contract Name
          </label>
          <input
            type="text"
            value={contractName}
            onChange={(e) => setContractName(e.target.value)}
            placeholder="MyContract"
            data-testid="contract-name-input"
            className="w-full px-3 py-2 text-sm bg-background border border-border rounded-none text-foreground placeholder:text-muted/50 focus:outline-none focus:border-border focus:ring-1 focus:ring-emerald-500/20 transition-all duration-150"
          />
          {isEmpty && (
            <p className="mt-1.5 text-[10px] text-foreground flex items-center gap-1">
              ⚠ Required
            </p>
          )}
        </div>

        {/* Storage Fields */}
        <div>
          <div className="flex items-center justify-between mb-1.5">
            <label className="text-[11px] text-muted uppercase tracking-widest">
              Storage Fields
            </label>
            <span className="text-[9px] text-muted/50 font-mono">
              {storageFields.length} field{storageFields.length !== 1 ? "s" : ""}
            </span>
          </div>

          {storageFields.length > 0 && (
            <div className="space-y-1.5 mb-2">
              {storageFields.map((field) => (
                <div key={field.id} className="flex flex-col gap-0.5">
                  <div className="flex items-center gap-1">
                    <input
                      type="text"
                      value={field.name}
                      onChange={(e) =>
                        updateStorageField(field.id, { name: e.target.value.replace(/[^a-zA-Z0-9_]/g, "") })
                      }
                      placeholder="field_name"
                      title={fieldNameError(field.name) ?? undefined}
                      className={`flex-1 min-w-0 px-2 py-1.5 text-[11px] font-mono bg-background border rounded-none text-foreground placeholder:text-muted/40 focus:outline-none transition-all duration-150 ${
                        field.name && !isValidFieldName(field.name)
                          ? "border-red-500/70 focus:border-red-500"
                          : "border-border focus:border-border"
                      }`}
                    />
                    <select
                      value={field.type}
                      onChange={(e) => updateStorageField(field.id, { type: e.target.value })}
                      className="w-[110px] px-1.5 py-1.5 text-[10px] font-mono bg-background border border-border rounded-none text-foreground focus:outline-none focus:border-border transition-all duration-150 appearance-none cursor-pointer"
                    >
                      {GENVM_TYPES.map((t) => (
                        <option key={t} value={t}>{t}</option>
                      ))}
                    </select>
                    <button
                      onClick={() => removeStorageField(field.id)}
                      className="p-1 text-muted/40 hover:text-red-400 transition-colors duration-150 shrink-0"
                    >
                      <X className="w-3 h-3" />
                    </button>
                  </div>
                  {field.name && !isValidFieldName(field.name) && (
                    <p className="text-[9px] text-red-400 pl-1">{fieldNameError(field.name)}</p>
                  )}
                </div>
              ))}
            </div>
          )}

          <button
            onClick={addStorageField}
            className="w-full flex items-center justify-center gap-1 px-2 py-1.5 text-[10px] font-medium text-foreground/70 hover:text-foreground border border-dashed border-border hover:border-border rounded-none bg-surface hover:bg-surface transition-all duration-150"
          >
            <Plus className="w-3 h-3" />
            Add Field
          </button>
        </div>

        {/* Constructor Args (Collapsible) */}
        <div>
          <button
            onClick={() => setShowCtorArgs(!showCtorArgs)}
            className="w-full flex items-center gap-1.5 text-[11px] text-muted/70 hover:text-muted transition-colors duration-150"
          >
            {showCtorArgs ? (
              <ChevronDown className="w-3 h-3" />
            ) : (
              <ChevronRight className="w-3 h-3" />
            )}
            <Wrench className="w-3 h-3" />
            <span className="uppercase tracking-widest">Constructor Args</span>
            {constructorArgs.length > 0 && (
              <span className="text-[9px] text-foreground/60 font-mono ml-auto">
                {constructorArgs.length}
              </span>
            )}
          </button>

          {showCtorArgs && (
            <div className="mt-2 space-y-1.5">
              {constructorArgs.map((arg) => (
                <div key={arg.id} className="flex flex-col gap-0.5">
                  <div className="flex items-center gap-1">
                    <input
                      type="text"
                      value={arg.name}
                      onChange={(e) =>
                        updateConstructorArg(arg.id, { name: e.target.value.replace(/[^a-zA-Z0-9_]/g, "") })
                      }
                      placeholder="arg_name"
                      title={fieldNameError(arg.name) ?? undefined}
                      className={`flex-1 min-w-0 px-2 py-1.5 text-[11px] font-mono bg-background border rounded-none text-foreground placeholder:text-muted/40 focus:outline-none transition-all duration-150 ${
                        arg.name && !isValidFieldName(arg.name)
                          ? "border-red-500/70 focus:border-red-500"
                          : "border-border focus:border-border"
                      }`}
                    />
                    <select
                      value={arg.type}
                      onChange={(e) => updateConstructorArg(arg.id, { type: e.target.value })}
                      className="w-[110px] px-1.5 py-1.5 text-[10px] font-mono bg-background border border-border rounded-none text-foreground focus:outline-none focus:border-border transition-all duration-150 appearance-none cursor-pointer"
                    >
                      {GENVM_TYPES.map((t) => (
                        <option key={t} value={t}>{t}</option>
                      ))}
                    </select>
                    <button
                      onClick={() => removeConstructorArg(arg.id)}
                      className="p-1 text-muted/40 hover:text-red-400 transition-colors duration-150 shrink-0"
                    >
                      <X className="w-3 h-3" />
                    </button>
                  </div>
                  {arg.name && !isValidFieldName(arg.name) && (
                    <p className="text-[9px] text-red-400 pl-1">{fieldNameError(arg.name)}</p>
                  )}
                </div>
              ))}
              <button
                onClick={addConstructorArg}
                className="w-full flex items-center justify-center gap-1 px-2 py-1.5 text-[10px] font-medium text-foreground/70 hover:text-foreground border border-dashed border-border hover:border-border rounded-none bg-surface hover:bg-surface transition-all duration-150"
              >
                <Plus className="w-3 h-3" />
                Add Arg
              </button>
            </div>
          )}
        </div>
      </div>

      {/* Source Handle (bottom) */}
      <Handle
        type="source"
        position={Position.Bottom}
        className="!w-3 !h-3"
      />
    </div>
  );
}
